version: "3.8"
services:
bridge:
build: .
ports:
- "8088:8088"
environment:
- PORT=8088
- LLM_BASE_URL=http://192.168.1.216:1234/v1
- LLM_MODEL=openai/gpt-oss-20b
- MCP_SERVERS=[{"name":"Home Assistant","sseUrl":"http://10.0.0.8:8123/mcp_server/sse","apiKey":"REDACT_ME"}]
restart: unless-stopped